### ISSUE TITLE
Datums op hoofdscherm

### ISSUE THREAD

**Issue by tjvomauricio** [swentel/gentsefeesten#85]
Op de hoofdscherm om 18:30 (local time) komen de shows van 20:30.

**Comment by swentel** [comment]
Dat is me inderdaad gisterenavond ook opgevallen, dju. De timestamps waren (eindelijk) UTC dit jaar, maar vergeten aan te passen op het startscherm, ik pas het straks aan en push een nieuwe release!

**Comment by swentel** [comment]
fixed
